[versions]
agp = "8.9.3"
adapterRxjava = "2.9.0"
appcompat = "1.7.0"
cardview = "1.0.0"
converterGson = "2.11.0"
compose-multiplatform = "1.7.3"
espressoCore = "3.6.1"
fineractClientCmp = "0.0.1"
fineractClientKmp = "1.0.5"
fineractClientKmpVersion = "1.0.5"
junit = "4.13.2"
junitVersion = "1.2.1"
koinAndroid = "4.0.1"
kotlin = "2.1.20"
kotlinStdlib = "2.1.20"
kotlinxCoroutinesAndroid = "1.10.2"
kotlinxSerializationJson = "1.8.1"
ktorClientOkhttp = "3.1.2"
ktorfitLib = "2.5.1"
ktorSerializationKotlinxJson = "3.1.3"
lifecycleExtensions = "2.2.0"
lifecycleRuntimeKtx = "2.9.0"
lifecycleViewmodelCompose = "2.8.3"
okhttp = "4.12.0"
preferenceKtx = "1.2.1"
rxandroid = "1.2.1"
rxjava = "1.3.8"
truth = "1.4.4"
androidx-activityCompose = "1.10.1"
compose = "1.8.1"
compose-material3 = "1.3.2"
material3Android = "1.3.2"
ui = "1.0.0"
uiToolingPreviewAndroid = "1.8.1"
hotReload = "1.0.0-alpha03"
kover = "0.9.1"
dokka = "1.9.20"
ksp = "2.1.21-2.0.1"
ktorfit = "2.5.1"
kotlinxDatetime = "0.6.2"
ktor = '3.1.3'





[libraries]

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
ktor-client-json = { group = "io.ktor", name = "ktor-client-json", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorClientOkhttp" }
ktor-client-serialization = { group = "io.ktor", name = "ktor-client-serialization", version.ref = "ktor" }
ktorfit-converters-flow = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-converters-flow", version.ref = "ktorfit" }
ktorfit-converters-call = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-converters-call", version.ref = "ktorfit" }
adapter-rxjava = { module = "com.squareup.retrofit2:adapter-rxjava", version.ref = "adapterRxjava" }
androidx-ui-test-junit4-android = { module = "androidx.compose.ui:ui-test-junit4-android", version.ref = "uiToolingPreviewAndroid" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiToolingPreviewAndroid" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "converterGson" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
fineract-client-cmp = { module = "com.github.openMF:fineract-client-cmp", version.ref = "fineractClientCmp" }
fineract-client-kmp = { module = "com.github.openMF:fineract-client-kmp", version.ref = "fineractClientKmp" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktorSerializationKotlinxJson" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktorSerializationKotlinxJson" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorSerializationKotlinxJson" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorSerializationKotlinxJson" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorSerializationKotlinxJson" }
ktor-network-tls-certificates = { module = "io.ktor:ktor-network-tls-certificates", version.ref = "ktorSerializationKotlinxJson" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorSerializationKotlinxJson" }
ktorfit-lib = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfitLib" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
niyajali-fineract-client-kmp = { module = "io.github.niyajali:fineract-client-kmp", version.ref = "fineractClientKmpVersion" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
rxandroid = { module = "io.reactivex:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex:rxjava", version.ref = "rxjava" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "uiToolingPreviewAndroid" }
ktorfit-ksp = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-ksp", version.ref = "ktorfit" }


[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kover = { id = 'org.jetbrains.kotlinx.kover', version.ref = 'kover' }
dokka = { id = 'org.jetbrains.dokka', version.ref = 'dokka' }
hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "hotReload" }
ksp = { id = 'com.google.devtools.ksp', version.ref = 'ksp' }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
